name: Most used
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.languages.svg
  token: ${{ secrets.METRICS_TOKEN }}
  base: ""
  plugin_languages: yes
  plugin_languages_indepth: yes
  plugin_languages_details: lines
  plugin_languages_ignored: >-
    dockerfile, makefile, qmake, lex, cmake, shell,
    gnuplot
  plugin_languages_limit: 10
