name: Most used
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: klim orlov, klimetzc, klimetzc@users.noreply.github.com
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 1000
          plugin_languages_details: lines
          plugin_languages_ignored: >-
            dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 8
          plugin_languages_colors: github
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
